In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('data/avocado.csv')
data.T

,0,1,2,3,4,5,6,7,8,9,...,18239,18240,18241,18242,18243,18244,18245,18246,18247,18248
Unnamed: 0,0,1,2,3,4,5,6,7,8,9,...,2,3,4,5,6,7,8,9,10,11
Date,27-12-2015,20-12-2015,13-12-2015,06-12-2015,29-11-2015,22-11-2015,15-11-2015,08-11-2015,01-11-2015,25-10-2015,...,11-03-2018,04-03-2018,25-02-2018,18-02-2018,11-02-2018,04-02-2018,28-01-2018,21-01-2018,14-01-2018,07-01-2018
AveragePrice,1.33,1.35,0.93,1.08,1.28,1.26,0.99,0.98,1.02,1.07,...,1.56,1.54,1.57,1.56,1.57,1.63,1.71,1.87,1.93,1.62
Total Volume,64236.62,54876.98,118220.22,78992.15,51039.6,55979.78,83453.76,109428.33,99811.42,74338.76,...,22128.42,17393.3,18421.24,17597.12,15986.17,17074.83,13888.04,13766.76,16205.22,17489.58
4046,1036.74,674.28,794.7,1132.0,941.48,1184.27,1368.92,703.75,1022.15,842.4,...,2162.67,1832.24,1974.26,1892.05,1924.28,2046.96,1191.7,1191.92,1527.63,2894.77
4225,54454.85,44638.81,109149.67,71976.41,43838.39,48067.99,73672.72,101815.36,87315.57,64757.44,...,3194.25,1905.57,2482.65,1928.36,1368.32,1529.2,3431.5,2452.79,2981.04,2356.13
4770,48.16,58.33,130.5,72.58,75.78,43.61,93.26,80.0,85.34,113.0,...,8.93,0.0,0.0,0.0,0.0,0.0,0.0,727.94,727.01,224.53
Total Bags,8696.87,9505.56,8145.35,5811.16,6183.95,6683.91,8318.86,6829.22,11388.36,8625.92,...,16762.57,13655.49,13964.33,13776.71,12693.57,13498.67,9264.84,9394.11,10969.54,12014.15
Small Bags,8603.62,9408.07,8042.21,5677.4,5986.26,6556.47,8196.81,6266.85,11104.53,8061.47,...,16510.32,13401.93,13698.27,13553.53,12437.35,13066.82,8940.04,9351.8,10919.54,11988.14
Large Bags,93.25,97.49,103.14,133.76,197.69,127.44,122.05,562.37,283.83,564.45,...,252.25,253.56,266.06,223.18,256.22,431.85,324.8,42.31,50.0,26.01
XLarge Bags,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
type,conventional,conventional,conventional,conventional,conventional,conventional,conventional,conventional,conventional,conventional,...,organic,organic,organic,organic,organic,organic,organic,organic,organic,organic
year,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,...,2018,2018,2018,2018,2018,2018,2018,2018,2018,2018
region,Albany,Albany,Albany,Albany,Albany,Albany,Albany,Albany,Albany,Albany,...,WestTexNewMexico,WestTexNewMexico,WestTexNewMexico,WestTexNewMexico,WestTexNewMexico,WestTexNewMexico,WestTexNewMexico,WestTexNewMexico,WestTexNewMexico,WestTexNewMexico

In [2]:
data['Day'], data['Month'] = data.Date.str[:2], data.Date.str[3:5]
data = data.drop(['Unnamed: 0', 'Date'],axis=1)

In [3]:
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
label_dict = defaultdict(LabelEncoder)
data[['region','type','Day','Month','year']] = data[['region','type','Day','Month','year']].apply(lambda x: label_dict[x.name].fit_transform(x))

In [6]:
from sklearn.model_selection import train_test_split
X = data
y = X.pop('AveragePrice')
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=9)

In [8]:
from keras.callbacks import ModelCheckpoint, EarlyStopping
filepath = "avocado-{epoch:02d}-{val_loss:.2f}.hdf5"
model_ckpt = ModelCheckpoint(filepath, monitor='val_loss',verbose=1,save_best_only=True, mode='auto')
es = EarlyStopping(monitor='val_loss', min_delta=1, patience=5, verbose=1,)
callbacks = [model_ckpt, es]

In [13]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(units=16, activation='relu', input_dim=13))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=1, activation='linear'))
model.compile(loss='mse', optimizer='adam')

In [15]:
model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs=40, batch_size=32)
model.evaluate(X_test, y_test)

Epoch 1/40
400/400 [==============================] - 0s 1ms/step - loss: 533.7534 - val_loss: 64.1334
Epoch 2/40
400/400 [==============================] - 0s 983us/step - loss: 14571.6309 - val_loss: 9970.5361
Epoch 3/40
400/400 [==============================] - 0s 1ms/step - loss: 849.9877 - val_loss: 58.9777
Epoch 4/40
400/400 [==============================] - 0s 1ms/step - loss: 156.7957 - val_loss: 41.6182
Epoch 5/40
400/400 [==============================] - 0s 1ms/step - loss: 116.0057 - val_loss: 26.1780
Epoch 6/40
400/400 [==============================] - 0s 1ms/step - loss: 90.1996 - val_loss: 21.0404
Epoch 7/40
400/400 [==============================] - 0s 992us/step - loss: 70.7756 - val_loss: 15.9634
Epoch 8/40
400/400 [==============================] - 0s 975us/step - loss: 57.2546 - val_loss: 12.9063
Epoch 9/40
400/400 [==============================] - 0s 1ms/step - loss: 46.1860 - val_loss: 10.1968
Epoch 10/40
400/400 [==============================] - 0s 989us/step - loss: 37.5205 - val_loss: 9.6453
Epoch 11/40
400/400 [==============================] - 0s 1ms/step - loss: 30.1997 - val_loss: 6.6510
Epoch 12/40
400/400 [==============================] - 0s 1ms/step - loss: 24.1398 - val_loss: 5.3204
Epoch 13/40
400/400 [==============================] - 0s 1ms/step - loss: 19.4011 - val_loss: 4.2122
Epoch 14/40
400/400 [==============================] - 0s 957us/step - loss: 14.9486 - val_loss: 5.9212
Epoch 15/40
400/400 [==============================] - 0s 958us/step - loss: 12.5461 - val_loss: 3.2205
Epoch 16/40
400/400 [==============================] - 0s 1ms/step - loss: 22.0184 - val_loss: 2.4840
Epoch 17/40
400/400 [==============================] - 0s 1ms/step - loss: 108.1117 - val_loss: 2.2579
Epoch 18/40
400/400 [==============================] - 0s 1ms/step - loss: 20.3080 - val_loss: 6.4898
Epoch 19/40
400/400 [==============================] - 0s 982us/step - loss: 1136.7657 - val_loss: 4.7591
Epoch 20/40
400/400 [==============================] - 0s 1ms/step - loss: 36.3072 - val_loss: 2.7159
Epoch 21/40
400/400 [==============================] - 0s 1ms/step - loss: 3.2155 - val_loss: 1.5706
Epoch 22/40
400/400 [==============================] - 0s 983us/step - loss: 1.9879 - val_loss: 1.2540
Epoch 23/40
400/400 [==============================] - 0s 1ms/step - loss: 1.2053 - val_loss: 0.7068
Epoch 24/40
400/400 [==============================] - 0s 1ms/step - loss: 0.7512 - val_loss: 0.5163
Epoch 25/40
400/400 [==============================] - 0s 1ms/step - loss: 0.5245 - val_loss: 1.4922
Epoch 26/40
400/400 [==============================] - 0s 1ms/step - loss: 0.4808 - val_loss: 0.3137
Epoch 27/40
400/400 [==============================] - 0s 985us/step - loss: 0.2760 - val_loss: 0.2438
Epoch 28/40
400/400 [==============================] - 0s 991us/step - loss: 0.2324 - val_loss: 0.3941
Epoch 29/40
400/400 [==============================] - 0s 1ms/step - loss: 0.3278 - val_loss: 0.1896
Epoch 30/40
400/400 [==============================] - 0s 1ms/step - loss: 0.2231 - val_loss: 0.2099
Epoch 31/40
400/400 [==============================] - 0s 1ms/step - loss: 2.3822 - val_loss: 12.7928
Epoch 32/40
400/400 [==============================] - 0s 1ms/step - loss: 9.1069 - val_loss: 1.3039
Epoch 33/40
400/400 [==============================] - 0s 1ms/step - loss: 0.3001 - val_loss: 0.1682
Epoch 34/40
400/400 [==============================] - 0s 1ms/step - loss: 0.5522 - val_loss: 0.3584
Epoch 35/40
400/400 [==============================] - 0s 988us/step - loss: 1.9312 - val_loss: 0.7252
Epoch 36/40
400/400 [==============================] - 0s 1ms/step - loss: 0.1869 - val_loss: 0.1622
Epoch 37/40
400/400 [==============================] - 0s 983us/step - loss: 1.7217 - val_loss: 0.1648
Epoch 38/40
400/400 [==============================] - 0s 1ms/step - loss: 0.1825 - val_loss: 0.1653
Epoch 39/40
400/400 [==============================] - 0s 1ms/step - loss: 0.1893 - val_loss: 0.1718
Epoch 40/40
400/400 [==============================] - 0s 1ms/step - loss: 0.1713 - val_loss: 0.2697
172/172 [==============================] - 0s 572us/step - loss: 0.2697

0.26972970366477966